# Generated by Django 4.1.7 on 2023-12-23 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('original_link', models.URLField()),
                ('unique_code', models.CharField(default='9fa9325a', max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('clicks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('inactive', 'INACTIVE'), ('active', 'ACTIVE')], default='active', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
