# Generated by Django 4.1.7 on 2023-12-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_urlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='unique_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
